# Generated by Django 4.2.7 on 2026-08-16 02:17

import core.utils
import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('event_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('excerpt', models.TextField(blank=True, help_text='Short teaser for the card. Auto-filled from the description if blank.', max_length=400)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to=core.utils.upload_path('events'), validators=[core.validators.validate_image_file])),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('publish_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Event',
                'ordering': ('-event_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('notice_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='notice date')),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('attachment', models.FileField(blank=True, help_text='PDF or Office document, max 4 MB.', upload_to=core.utils.upload_path('notices'), validators=[core.validators.validate_document_file])),
                ('external_url', models.CharField(blank=True, max_length=300)),
                ('is_important', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('publish_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Notice',
                'ordering': ('-notice_date', '-created_at'),
                'indexes': [models.Index(fields=['is_published', '-notice_date'], name='events_noti_is_publ_75b11a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('image', models.ImageField(upload_to=core.utils.upload_path('events'), validators=[core.validators.validate_image_file])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='events.event')),
            ],
            options={
                'verbose_name': 'Event photo',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published', '-event_date'], name='events_even_is_publ_f1f540_idx'),
        ),
    ]
