# Generated by Django 4.2.7 on 2026-08-16 02:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='visible on site')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Admission step',
                'ordering': ('order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='visible on site')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=1000)),
                ('percentage', models.CharField(blank=True, help_text='e.g. Up to 100%', max_length=40)),
                ('criteria', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scholarship',
                'ordering': ('order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='visible on site')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name': 'State',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='visible on site')),
                ('name', models.CharField(max_length=80)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='admissions.state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('state', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('full_name', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Name may only contain letters, spaces, apostrophes, dots and hyphens.', regex="^[A-Za-z][A-Za-z .'\\-]{1,79}$")])),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number (starting 6-9).', regex='^[6-9]\\d{9}$')])),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_text', models.TextField(blank=True, editable=False)),
                ('source_page', models.CharField(blank=True, editable=False, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user_agent', models.CharField(blank=True, editable=False, max_length=300)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=12)),
                ('staff_notes', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='admissions.city')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='academics.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='academics.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='academics.program', verbose_name='programme level')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='academics.school')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='admissions.state')),
            ],
            options={
                'verbose_name': 'Admission enquiry',
                'verbose_name_plural': 'Admission enquiries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='admissions__status_ec1fd9_idx'), models.Index(fields=['email'], name='admissions__email_6c53f0_idx')],
            },
        ),
    ]
