# Generated by Django 4.2.7 on 2026-08-16 02:17

import core.utils
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='visible on site')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=core.utils.upload_path('facilities'), validators=[core.validators.validate_image_file])),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ('order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='visible on site')),
                ('name', models.CharField(max_length=160)),
                ('logo', models.ImageField(blank=True, upload_to=core.utils.upload_path('partners'), validators=[core.validators.validate_image_file])),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Industry partner',
                'ordering': ('order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='visible on site')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Programme level',
                'verbose_name_plural': 'Programme levels',
                'ordering': ('order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='visible on site')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('card_image', models.ImageField(blank=True, help_text='Shown on the home-page carousel card (approx. 700x400 px).', upload_to=core.utils.upload_path('schools'), validators=[core.validators.validate_image_file])),
                ('banner_image', models.ImageField(blank=True, upload_to=core.utils.upload_path('schools'), validators=[core.validators.validate_image_file])),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'School',
                'ordering': ('order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='visible on site')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('head_name', models.CharField(blank=True, max_length=120)),
                ('head_designation', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, upload_to=core.utils.upload_path('departments'), validators=[core.validators.validate_image_file])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.school')),
            ],
            options={
                'verbose_name': 'Department',
                'ordering': ('order', '-created_at'),
                'abstract': False,
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='visible on site')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. 4 Years / 8 Semesters', max_length=60)),
                ('eligibility', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('total_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.program', verbose_name='programme level')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.school')),
            ],
            options={
                'verbose_name': 'Course',
                'ordering': ('order', '-created_at'),
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'is_featured'], name='academics_c_is_acti_7237ba_idx')],
                'unique_together': {('school', 'name', 'program')},
            },
        ),
    ]
